"""posts and user followers

Revision ID: 355af03a6325
Revises: d4595777e0d3
Create Date: 2021-04-13 12:19:38.268213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '355af03a6325'
down_revision = 'd4595777e0d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
