"""image field in user model

Revision ID: d4595777e0d3
Revises: 15f55d5fba79
Create Date: 2021-04-11 00:53:37.884462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4595777e0d3'
down_revision = '15f55d5fba79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_img', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'user', ['avatar_img'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'avatar_img')
    # ### end Alembic commands ###
